gui/fetch/urls.py
from django.conf.urls import patterns, url

from fetch import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index')
	url(r'^execute1$', views.execute1, name='execute1'),
)

gui/gui/urls.py
from django.conf.urls import patterns, include, url


# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'gui.views.home', name='home'),
    # url(r'^gui/', include('gui.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
	
	#url(r'^$', 'fetch.views.index', name='index'),
	url(r'^$', 'fetch.views.main', name='main'),
	url(r'^index', 'fetch.views.index', name='index'),
	url(r'^execute1', 'fetch.views.execute1', name='execute1'),
	url(r'^upload', 'fetch.views.upload', name='upload'),
	url(r'^craft','fetch.views.craft',name='craft'),
	url(r'^result','fetch.views.result',name='result'),
	url(r'^execute2', 'fetch.views.execute2', name='execute2'),
)

gui/fetch/models.py
from django.db import models

# Create your models here.

gui/fetch/forms.py
#List of Forms that are going to be displayed to the user
from django import forms

#Form used for pickup a pcap option
class GetForm(forms.Form):
	sourceip = forms.CharField(required=False)
	sourcemac = forms.CharField(required=False)
	destip = forms.CharField(required=False)
	destmac = forms.CharField(required=False)
	srcport = forms.CharField(required=False)
	dstport = forms.CharField(required=False)
	destination = forms.CharField()

#Form used for crafting Ether pcap 
class FormEther(forms.Form):
	packets_count = forms.IntegerField(required=False)	
	srcmac_ether = forms.CharField(required=False)
	dstmac_ether = forms.CharField(required=False)
	type_ether = forms.CharField(required=False)
	src_ip = forms.CharField(required=False)
	dst_ip = forms.CharField(required=False)
	a = forms.CharField()
		
#Form used for crafting IP pcap
class FormIP(forms.Form):
	packets_count = forms.IntegerField(required=False)	
	srcmac_ether = forms.CharField(required=False)
	dstmac_ether = forms.CharField(required=False)
	src_ip = forms.CharField(required=False)
	dst_ip = forms.CharField(required=False)
	ihl_ip = forms.CharField(required=False)
	len_ip = forms.CharField(required=False)
	proto_ip = forms.CharField(required=False)
	version_ip = forms.CharField(required=False)
	chksum_ip = forms.CharField(required=False)
	flags_ip = forms.CharField(required=False)
	b = forms.CharField()

#Form used for crafting TCP pcap
class FormTCP(forms.Form):
	packets_count = forms.IntegerField(required=False)
	srcmac_ether = forms.CharField(required=False)
	dstmac_ether = forms.CharField(required=False)
	type_ether = forms.CharField(required=False)
	src_ip = forms.CharField(required=False)
	dst_ip = forms.CharField(required=False)
	ihl_ip = forms.CharField(required=False)
	len_ip = forms.CharField(required=False)
	proto_ip = forms.CharField(required=False)
	version_ip = forms.CharField(required=False)
	chksum_ip = forms.CharField(required=False)
	flags_ip = forms.CharField(required=False)
	sport_tcp = forms.CharField(required=False)
	dport_tcp = forms.CharField(required=False)
	dataofs_tcp = forms.CharField(required=False)
	chksum_tcp = forms.CharField(required=False)
	c = forms.CharField()

#Form used for crafting UDP pcap
class FormUDP(forms.Form):
	packets_count = forms.IntegerField(required=False)
	srcmac_ether = forms.CharField(required=False)
	dstmac_ether = forms.CharField(required=False)
	type_ether = forms.CharField(required=False)
	src_ip = forms.CharField(required=False)
	dst_ip = forms.CharField(required=False)
	ihl_ip = forms.CharField(required=False)
	len_ip = forms.CharField(required=False)
	proto_ip = forms.CharField(required=False)
	version_ip = forms.CharField(required=False)
	chksum_ip = forms.CharField(required=False)
	flags_ip = forms.CharField(required=False)
	sport_udp = forms.CharField(required=False)
	dport_udp = forms.CharField(required=False)
	chksum_udp = forms.CharField(required=False)
	len_udp = forms.CharField(required=False)
	d = forms.CharField()

#Form used for crafting ICMP pcap
class FormICMP(forms.Form):
	packets_count = forms.IntegerField(required=False)
	srcmac_ether = forms.CharField(required=False)
	dstmac_ether = forms.CharField(required=False)
	type_ether = forms.CharField(required=False)
	src_ip = forms.CharField(required=False)
	dst_ip = forms.CharField(required=False)
	ihl_ip = forms.CharField(required=False)
	len_ip = forms.CharField(required=False)
	proto_ip = forms.CharField(required=False)
	version_ip = forms.CharField(required=False)
	chksum_ip = forms.CharField(required=False)
	flags_ip = forms.CharField(required=False)
	type_icmp = forms.CharField(required=False)
	code_icmp = forms.CharField(required=False)
	chksum_icmp = forms.CharField(required=False)
	e = forms.CharField()






	

gui/fetch/views.py
'''
views.py --
	General Information
	File owner : Manoj Tammali
	Description : Python program getting the requests from the web pages and
		      providing the results back to the user,using back end program
'''
import sys
from scapy.all import *
from django.template.loader import get_template
from django.template import Context
from django.shortcuts import render, redirect
from fetch.forms import GetForm,FormIP, FormEther, FormTCP, FormUDP, FormICMP
from tool import fun1, fun2, fun3, fun4, fun5, fun6, fun7, fun8, fun9, fun10, fun11, fun12, fun13, fun14, fun15, fun16,fun17,fun18
import os, shutil, dpkt
from scapy.error import Scapy_Exception

#Displaying main.html form
def main(request):
	return render(request,'main.html',{
	})	
#Displaying index,html form
def index(request):
	return render(request, 'index.html', {
		'form' : GetForm(),
	})
#Handling the index form submitted in execute1 function 
def execute1(request):
	filepath = ""
	if request.method == "POST":
		form = GetForm(request.POST)
		if form.is_valid():
			values = form.cleaned_data
			route = values['destination']
			#Retreiving all the field values of the form by using hidden field and calling appropriate functions in backend program
			if route == 'etheronly':

				filepath = fun1(values['sourceip'],values['sourcemac'],values['destip'],values['destmac'])

			elif route == 'etherudp':

				filepath = fun2(values['sourceip'],values['sourcemac'],values['destip'],values['destmac'],values['srcport'],values['dstport'])

			elif route == 'ethertcp':

                                filepath = fun3(values['sourceip'],values['sourcemac'],values['destip'],values['destmac'],values['srcport'],values['dstport'])
                                
	                elif route == 'ethericmp':
                                
				filepath = fun4(values['sourceip'],values['sourcemac'],values['destip'],values['destmac'])

			elif route == 'security':
				
				filepath = fun5(values['sourceip'],values['sourcemac'],values['destip'],values['destmac'])

 			elif route == 'TCP':
		
				filepath = fun6(values['sourceip'],values['sourcemac'],values['destip'],values['destmac'],values['srcport'],values['dstport'])

			elif route == 'UDP':

				filepath = fun7(values['sourceip'],values['sourcemac'],values['destip'],values['destmac'],values['srcport'],values['dstport'])

			elif route == 'ICMP':

				filepath = fun8(values['sourceip'],values['sourcemac'],values['destip'],values['destmac'])

			elif route == 'EtherIPV4':

				filepath = fun9(values['sourceip'],values['sourcemac'],values['destip'],values['destmac'])

			elif route == 'EtherIPV4ICMP':

				filepath = fun10(values['sourceip'],values['sourcemac'],values['destip'],values['destmac'])

			elif route == 'EtherIPV4TCP':

				filepath = fun11(values['sourceip'],values['sourcemac'],values['destip'],values['destmac'],values['srcport'],values['dstport'])

			elif route == 'EtherIPV4UDP':

				filepath = fun12(values['sourceip'],values['sourcemac'],values['destip'],values['destmac'],values['srcport'],values['dstport'])
			
			elif route == 'IPV4':
				filepath = fun13(values['sourceip'],values['sourcemac'],values['destip'],values['destmac'])

			elif route == 'IPV4TCP':
				filepath = fun14(values['sourceip'],values['sourcemac'],values['destip'],values['destmac'],values['srcport'],values['dstport'])

			elif route =='IPV4UDP':

			 	filepath = fun15(values['sourceip'],values['sourcemac'],values['destip'],values['destmac'],values['srcport'],values['dstport'])

			elif route == 'IPV4ICMP':
				filepath = fun16(values['sourceip'],values['sourcemac'],values['destip'],values['destmac'])

			elif route == 'IPoptions':
				filepath = fun17(values['sourceip'],values['sourcemac'],values['destip'],values['destmac'])

			elif route == 'ARP':
				filepath = fun18(values['sourceip'],values['sourcemac'],values['destip'],values['destmac'])
			

	
	return render(request, 'execute1.html', {
					'filepath': filepath
						})	
#Displaying upload html form and handling file submitted in that form
def upload(request):
	if request.method == "POST":
		myFile = request.FILES['myfile']
	
		TEMP_DEST = 'fetch/garbage'
		with open(TEMP_DEST, 'wb') as dest:
			shutil.copyfileobj(myFile,dest)
		try:
			_ = dpkt.pcap.Reader(open(TEMP_DEST))
		except:
			#File Thrown if not a valid pcap file
			return render(request, 'upload.html', {'fileUploaded':"Invalid File. Thrown into garbage"})
		
		DEST_DIR = 'fetch/repository/'
		destPath = os.path.join(DEST_DIR, myFile.name)
		#Check to dicard conflicting name pcaps that are already existing in repository when tried to upload
		if os.path.exists(destPath):
			return render(request, 'upload.html', {"fileUploaded": "File with that name already exists,file not uploaded"})
		#Copying all the file data into desired location
		with open(destPath, 'wb') as dest:
			with open(TEMP_DEST, 'rb') as source:
				shutil.copyfileobj(source, dest)
		#Modifying the pcap contents as per the repository standards		
                pkt = rdpcap('fetch/repository/' + myFile.name)
		i=0
		while i < len(pkt):
			if pkt[i].haslayer(IP):
				pkt[i][IP].src = "192.168.10.10"
				pkt[i][IP].dst = "192.168.10.20"
			if pkt[i].haslayer(Ether):
				pkt[i][Ether].src = "00:50:56:01:02:03"
				pkt[i][Ether].dst = "00:50:56:04:05:06"
			i=i+1
		wrpcap('fetch/repository/'+myFile.name,pkt)	
                				
		return render(request, 'upload.html', {'fileUploaded': "Uploaded file " + myFile.name,})
	else:
		return render(request, 'upload.html', {'fileUploaded':"",})

#Function to handle crafting packets logic
def craft(request):
	
	return render(request,'craft.html', {
		'formether' : FormEther(),
		'formip' : FormIP(),
		'formtcp' : FormTCP(),
		'formicmp' : FormICMP(),
		'formudp' : FormUDP()
	})
#Function to retrieve submitted data from the craft forms and craft packets and give back to user appropriately
def result(request):

	if request.method == 'POST':
		data = request.POST
		#Retreiving the submitted form by using hidden field		
		if 'a' in data:
			form = FormEther(data)		
			if form.is_valid():
				
				values = form.cleaned_data
				length = values.pop('packets_count')
				del values['a']
				
				#Field values checks appropriately done 	
					
				totallist = []
				fields = ('srcmac_ether', 'dstmac_ether', 'type_ether', 'src_ip', 'dst_ip')
				for key in fields:
					if values[key] == '':
						#Atleast one value in each field check
						return render(request, 'goback.html', {
                                                'errormsg': "Specify atleast one value in each field"
                                                })
					#Retrieve values specified in appropriate field
					elif key == 'type_ether':
						packets = []
						types = values[key].split(',')
						for i in xrange(len(types)):
							if '-' in types[i]:
								pair = types[i].split('-')
								start= int(pair[0],16)
								end= int(pair[1],16)+1
								if start > end:
									packets.extend(range(start,end,-1))
								else:
									packets.extend(range(start,end))
							else:
								packets.append(int(types[i],16))	
						
					else:
						packets = values[key].split(',')
					
					provided = len(packets)
					
					if provided < length:
						for i in xrange(length - provided):
							packets.append(packets[i % provided])
				
					
					elif provided != length and length is not None:
						#print provided, length
						return render(request, 'goback.html', {
						'errormsg': "You Entered less num of packets compared to some field values,go back and correct it"
						})
					totallist.append(packets)
				pktlist = []
				# if packets count is None, take all possible combinations to generate packets
				if length is None:
					for srcmac in totallist[0]:
						for dstmac in totallist[1]:
							for type_ in totallist[2]:
								for srcip in totallist[3]:
									for dstip in totallist[4]:
										pkt = Ether(src=srcmac, dst=dstmac, type=type_) / IP(src=srcip, dst=dstip)
										pktlist += [p for p in pkt]
				# else packets count specified, limit the packets to be generated
				else:
					for j in range(0,length):		
						pkt=Ether(src=totallist[0][j],dst=totallist[1][j],type=totallist[2][j])/IP(src=totallist[3][j],dst=totallist[4][j])
						pktlist += [p for p in pkt]
		
				wrpcap('fetch/static/Ether_craft.cap',pktlist)
        			filepath = 'Ether_craft.cap'

				return render(request, 'result.html', {
                                        'filepath': filepath
                                                })

		if 'b' in data:
			form = FormIP(data)
			if form.is_valid():
				values = form.cleaned_data
				length = values.pop('packets_count')
				del values['b']
				#Field values checks appropriately done
				totallist = []
				fields = ('srcmac_ether', 'dstmac_ether', 'src_ip', 'dst_ip','ihl_ip','len_ip','proto_ip','version_ip','chksum_ip','flags_ip')
				for key in fields:
					if values[key] == '':
						#Atleast one value in each field check
						return render(request, 'goback.html', {
                                                'errormsg': "Specify atleast one value in each field"
                                                })

					#Retrieve values specified in appropriate field
					elif key == 'ihl_ip' or key == 'len_ip' or key == 'proto_ip' or key == 'version_ip':
                                                packets = []
                                                types = values[key].split(',')
                                                for i in xrange(len(types)):
                                                        if '-' in types[i]:
                                                                pair = types[i].split('-')
                                                                start= int(pair[0])
                                                                end= int(pair[1])+1
								if start > end:

gui/fetch/templates/craft.html
<!-- 	File owner : Manoj Tammali
	Description : Form taking input from user regarding crafting pcap option
-->
<html>
<head>
<script src="{{ STATIC_URL }}/jquery-1.10.2.min.js"></script>
<script type="text/javascript">

$(document).ready(function() {
        
        $('#layer4').off('click').on('click',function(e) {
                $('#div1').show();
                $('#div2').hide();
                $('#div3').hide();
                $('#div4').hide();
                $('#div5').hide();
		$('#div6').hide();
		$('#div7').hide();
		$('#div8').hide();		
        });

	$('#layer3').off('click').on('click',function(e) {
                $('#div1').hide();
                $('#div2').show();
                $('#div3').hide();
                $('#div4').hide();
                $('#div5').hide();
		$('#div6').hide();
		$('#div7').hide();
		$('#div8').hide();		
        });
	$('#layer2').off('click').on('click',function(e) {
                $('#div1').hide();
                $('#div2').hide();
                $('#div3').show();
                $('#div4').hide();
                $('#div5').hide();
		$('#div6').hide();
		$('#div7').hide();
		$('#div8').hide();		
        });
	
	$('#ip4').click(function(e) {
                $('#div1').hide();
                $('#div2').hide();
                $('#div3').hide();
                $('#div4').hide();
                $('#div5').hide();
		$('#div6').hide();
		
		$('#div8').hide();
		$('#id_b').val('ip4');
		$('form#7').find('#id_packets_count').val('1000');
		$('form#7').find('#id_srcmac_ether').val('00:50:56:01:02:03');
		$('form#7').find('#id_dstmac_ether').val('00:50:56:04:05:06');
		$('form#7').find('#id_src_ip').val('192.168.10.10');
		$('form#7').find('#id_dst_ip').val('192.168.10.20');
		$('form#7').find('#id_ihl_ip').val('5');
		$('form#7').find('#id_len_ip').val('20');
		$('form#7').find('#id_proto_ip').val('0');
		$('form#7').find('#id_version_ip').val('4');
		$('form#7').find('#id_chksum_ip').val('0x0');
		$('form#7').find('#id_flags_ip').val('0x0');
	
		$('#div7').show();
        });

	$('#ether').off('click').on('click',function(e) {
		
           	$('#div8').show();
	        $('#div1').hide();
                $('#div2').hide();
                $('#div3').hide();
                $('#div4').hide();
                $('#div5').hide();
		$('#div6').hide();
		$('#div7').hide();
		$('#id_a').val('ether');
		$('form#8').find('#id_packets_count').val('1000');
		$('form#8').find('#id_srcmac_ether').val('00:50:56:01:02:03');
		$('form#8').find('#id_dstmac_ether').val('00:50:56:04:05:06');
		$('form#8').find('#id_type_ether').val('0x800');
		$('form#8').find('#id_src_ip').val('192.168.10.10');
		$('form#8').find('#id_dst_ip').val('192.168.10.20');
	
        });

	$('#layer4-tcp').off('click').on('click',function(e) {
                $('#div1').hide();
                $('#div2').hide();
                $('#div3').hide();
                
                $('#div5').hide();
		$('#div6').hide();
		$('#div7').hide();
		$('#div8').hide();
		$('#id_c').val('tcp');
		$('form#4').find('#id_packets_count').val('1000');
		$('form#4').find('#id_srcmac_ether').val('00:50:56:01:02:03');
		$('form#4').find('#id_dstmac_ether').val('00:50:56:04:05:06');
		$('form#4').find('#id_type_ether').val('0x800');
		$('form#4').find('#id_src_ip').val('192.168.10.10');
		$('form#4').find('#id_dst_ip').val('192.168.10.20');
		$('form#4').find('#id_ihl_ip').val('5');
		$('form#4').find('#id_len_ip').val('40');
		$('form#4').find('#id_proto_ip').val('6');
		$('form#4').find('#id_version_ip').val('4');
		$('form#4').find('#id_chksum_ip').val('0x0');
		$('form#4').find('#id_flags_ip').val('0x0');
		$('form#4').find('#id_sport_tcp').val('21');
		$('form#4').find('#id_dport_tcp').val('23');
		$('form#4').find('#id_dataofs_tcp').val('5');
		$('form#4').find('#id_chksum_tcp').val('0x0');
		$('#div4').show();
							
        });
	$('#layer4-udp').off('click').on('click',function(e) {
                $('#div1').hide();
                $('#div2').hide();
                $('#div3').hide();
                $('#div4').hide();
               
		$('#div6').hide();
		$('#div7').hide();
		$('#div8').hide();
		$('#id_d').val('udp');
	  	$('form#5').find('#id_packets_count').val('1000');
                $('form#5').find('#id_srcmac_ether').val('00:50:56:01:02:03');
                $('form#5').find('#id_dstmac_ether').val('00:50:56:04:05:06');
                $('form#5').find('#id_type_ether').val('0x800');
                $('form#5').find('#id_src_ip').val('192.168.10.10');
                $('form#5').find('#id_dst_ip').val('192.168.10.20');
                $('form#5').find('#id_ihl_ip').val('5');
                $('form#5').find('#id_len_ip').val('28');
                $('form#5').find('#id_proto_ip').val('17');
                $('form#5').find('#id_version_ip').val('4');
                $('form#5').find('#id_chksum_ip').val('0x0');
                $('form#5').find('#id_flags_ip').val('0x0');
                $('form#5').find('#id_sport_udp').val('21');
                $('form#5').find('#id_dport_udp').val('23');
                $('form#5').find('#id_len_udp').val('5');
                $('form#5').find('#id_chksum_udp').val('0x0');
                $('#div5').show();
        });

	$('#layer4-icmp').off('click').on('click',function(e) {
                $('#div1').hide();
                $('#div2').hide();
                $('#div3').hide();
                $('#div4').hide();
                $('#div5').hide();
		$('#div6').show();
		$('#div7').hide();
		$('#div8').hide();
		$('#id_e').val('icmp');
		$('form#6').find('#id_packets_count').val('1000');
		$('form#6').find('#id_srcmac_ether').val('00:50:56:01:02:03');
		$('form#6').find('#id_dstmac_ether').val('00:50:56:04:05:06');
		$('form#6').find('#id_type_ether').val('0x800');
		$('form#6').find('#id_src_ip').val('192.168.10.10');
		$('form#6').find('#id_dst_ip').val('192.168.10.20');
		$('form#6').find('#id_ihl_ip').val('5');
		$('form#6').find('#id_len_ip').val('28');
		$('form#6').find('#id_proto_ip').val('1');
		$('form#6').find('#id_version_ip').val('4');
		$('form#6').find('#id_chksum_ip').val('0x0');
		$('form#6').find('#id_flags_ip').val('0x0');
		$('form#6').find('#id_type_icmp').val('8');
		$('form#6').find('#id_code_icmp').val('0');
		$('form#6').find('#id_chksum_icmp').val('0x0');
        });
 
	$('#id_a').hide();
        $('label[for=id_a]').hide();
	$('#id_b').hide();
        $('label[for=id_b]').hide();
	$('#id_c').hide();
        $('label[for=id_c]').hide();
	$('#id_d').hide();
        $('label[for=id_d]').hide();
	$('#id_e').hide();
        $('label[for=id_e]').hide();
});

</script> 
</head>

<body style="background-color:#5A5097">

<div id="div-main">
{{ errormsg }}
<p><b><u>Select which layered packets you want to craft</u></b></p><br>
<input type="radio" id="layer4" name="layer" value="layer4"/>
<label for="layer4">Craft Layer 4 packets </label>

<input type="radio" id="layer3" name="layer" value="layer3"/>
<label for="layer3">Craft Layer 3 packets </label>

<input type="radio" id="layer2" name="layer" value="layer2"/>
<label for="layer2">Craft Layer 2 packets </label>

</div>

<div id="div1" style="display:none;">
<p><b><u>Select which layer among layer4 </u></b></p>
<input type="radio" id="layer4-tcp" name="layer" value="layer4-tcp"/>
<b><label for="layer4-tcp">TCP layered</label></b> - Fields of Ether, IP and TCP layers can be modified
<br><br>
<input type="radio" id="layer4-udp" name="layer" value="layer4-udp"/>
<b><label for="layer4-udp">UDP layered</label></b> - Fields of Ether, IP and UDP layers can be modified
<br><br>
<input type="radio" id="layer4-icmp" name="layer" value="layer4-icmp"/>
<b><label for="layer4-icmp">ICMP layered</label></b> - Fields of Ether, IP and ICMP layers can be modified
<br>
</div>

<div id="div2" style="display:none;">
<p><b><u>Select which layer among layer3</u></b></p>
<input type="radio" id="ip4" name="layer" value="ip4"/>
<b><label for="ip4">IPV4</label></b> - Fields of Ether , IP layers can be modified
</div>



<div id="div3" style="display:none;">
<p><b><u>Select which layer among layer2</u></b></p>
<input type="radio" id="ether" name="layer" value="ether"/>
<b><label for="ether">Ether</label></b> - Ether Fields can be modified
</div>

<div id="div4" style="display:none;">
<p align="center" ><b><u>INSTRUCTIONS TO FILL THE FORM</u></b><br><br>
1.specifying packets count is optional but all the other fields must have atleast one value<br><br>2.All Fields are filled with some default values, edit them to generate your own packets <br><br>3.Can specify either ranges or comma seperated values as inputs for Integer type Fields<br><br>4.Make sure you request more packets than the number of values you specified for each field
</p>
<p><b>Enter values:</b></p>
<form id="4" action="result" method="POST">
{% csrf_token %}
<table>
{{ formtcp.as_table }}
</table>
<input type="submit" id="submit" value="submit" />
</form>
</div>

<div id="div5" style="display:none;">
<p align="center" ><b><u>INSTRUCTIONS TO FILL THE FORM</u></b><br><br>
1.specifying packets count is optional but all the other fields must have atleast one value<br><br>2.All Fields are filled with some default values, edit them to generate your own packets <br><br>3.Can specify either ranges or comma seperated values as inputs for Integer type Fields<br><br>4.Make sure you request more packets than the number of values you specified for each field
</p>
<p><b>Enter values:</b></p>
<form id="5" action="result" method="POST">
{% csrf_token %}
<table>
{{ formudp.as_table }}
</table>
<input type="submit" id="submit" value="submit" />
</form>
</div>

<div id="div6" style="display:none;">
<p align="center" ><b><u>INSTRUCTIONS TO FILL THE FORM</u></b><br><br>
1.specifying packets count is optional but all the other fields must have atleast one value<br><br>2.All Fields are filled with some default values, edit them to generate your own packets <br><br>3.Can specify either ranges or comma seperated values as inputs for Integer type Fields<br><br>4.Make sure you request more packets than the number of values you specified for each field
</p>
<p><b>Enter values:</b></p>
<form id="6" action="result" method="POST">
{% csrf_token %}
<table>
{{ formicmp.as_table }}
</table>

<input type="submit" id="submit" value="submit" />
</form>
</div>

<div id="div7" style="display:none;">
<p align="center" ><b><u>INSTRUCTIONS TO FILL THE FORM</u></b><br><br>
1.specifying packets count is optional but all the other fields must have atleast one value<br><br>2.All Fields are filled with some default values, edit them to generate your own packets <br><br>3.Can specify either ranges or comma seperated values as inputs for Integer type Fields<br><br>4.Make sure you request more packets than the number of values you specified for each field
</p>
<p><b>Enter values:</b></p>
<form id="7" action="result" method="POST">

{% csrf_token %}
<table>
{{ formip.as_table }}
</table>

<input type="submit" id="submit" value="submit" />
</form>
</div>


<div id="div8" style="display:none;">
<p align="center" ><b><u>INSTRUCTIONS TO FILL THE FORM</u></b><br><br>
1.specifying packets count is optional but all the other fields must have atleast one value<br><br>2.All Fields are filled with some default values, edit them to generate your own packets <br><br>3.Can specify either ranges or comma seperated values as inputs for Integer type Fields<br><br>4.Make sure you request more packets than the number of values you specified for each field
</p>
<p><b>Enter values:</b></p>
<form id="8" action="result" method="POST">
{% csrf_token %}
<table>
{{ formether.as_table }}
</table>
<input type="submit" id="submit" value="submit" />
</form>
</div>
</body>
</html>

gui/fetch/templates/execute1.html
<!DOCTYPE html giving the user the file modified from the repository based on his choice>
<html>
<body style="background-color:#B6B1D1">
<p><b>please Click on the link to download requested Pcap file</b></p>
<br>
Download File :
<a href="{{ STATIC_URL}}{{filepath}}">{{ filepath }}</a>
</body>
</html>

gui/fetch/templates/goback.html
<!-- Error msg html form for invalid user input 
-->
<html>
<body style="background-color:#B6B1D1">
<br><p><b>{{ errormsg }}</b></p>
</body>
</html>

gui/fetch/templates/result.html
<!--  Providing the user with crafted file based on his input
 -->
<html>
<body style="background-color:#B6B1D1">
<p><b>Please Click on the link to download the Crafted Pcap file</b></p>
Download File :
<a href="{{ STATIC_URL}}{{filepath}}">{{filepath}}</a>
</body>
</html>